apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: glusterfs-storage-xxx
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://192.168.1.27:8080"
  restuser: "user"
  restuserkey: "user:Irv6t2DnQVA5D2wA"
